# Generated by Django 2.0.7 on 2019-03-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signInDetaila',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
