# Generated by Django 2.0.7 on 2019-03-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signInDetaila',
            new_name='signInDetails',
        ),
    ]
