# Generated by Django 2.0.7 on 2019-03-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('groupName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('friend1', models.CharField(max_length=40)),
                ('friend2', models.CharField(max_length=40)),
                ('friend3', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='groups',
        ),
    ]
