# Generated by Django 2.0.7 on 2019-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190328_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='you',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
