# Generated by Django 2.0.7 on 2019-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_group_you'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='email',
            new_name='friend1email',
        ),
        migrations.AddField(
            model_name='group',
            name='friend2email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='friend3email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='yoursemail',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
