# Generated by Django 2.0.9 on 2019-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190329_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('groupName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalexpense', models.CharField(max_length=10)),
                ('you', models.CharField(max_length=10)),
                ('friend1', models.CharField(max_length=10)),
                ('friend2', models.CharField(max_length=10)),
                ('friend3', models.CharField(max_length=10)),
            ],
        ),
    ]
